# .streamlit/secrets.toml
password_hash = "1fc2d314721b9811e78e30fdcad5031680172b2cc9c692c5226905632513a174"
secret_key = "app"


# MongoDB connection string
mongo_uri = "mongodb://clinicog:rfh4HTX2tkd9mjr1qca@5.196.94.125:27017/"

#  MongoDB components
[mongo]
host = "5.196.94.125"
port = 27017
username = "clinicog"
password = "rfh4HTX2tkd9mjr1qca"
database_name = "Questionnaire"  
